language: php

matrix:
  include:
  - php: 5.6
  - php: 7.0

before_install:
  - openssl aes-256-cbc -K $encrypted_98dcc32c9b33_key -iv $encrypted_98dcc32c9b33_iv -in auth.json.enc -out auth.json -d

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - composer validate
  - "./vendor/bin/phing sniff"
  - "./vendor/bin/phing unit"
