# Based on Mark Shust's Docker Configuration for Magento Version 22.0.0
# https://github.com/markshust/docker-magento

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13-7
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer
      - ~/.composer/auth.json:/var/www/html/auth.json
      - ./:/var/www/BitExpert/ForceCustomerLogin/
      - ./dist:/dist
      - appdata:/var/www/html
      - sockdata:/sock

  phpfpm:
    image: markoshust/magento-php:7.2-fpm-0
    links:
      - db
    volumes: *appvolumes

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  appdata:
  dbdata:
  sockdata:
