# Mage Inferno Docker Compose (https://github.com/mageinferno/magento2-docker-compose)
# Version 7.0.0

version: "3"

services:
  app:
    image: mageinferno/magento2-nginx:1.11-1
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - appdata:/var/www/html
      - ./Api:/var/www/html/app/code/BitExpert/ForceCustomerLogin/Api:cached
      - ./Block:/var/www/html/app/code/BitExpert/ForceCustomerLogin/Block:cached
      - ./Controller:/var/www/html/app/code/BitExpert/ForceCustomerLogin/Controller:cached
      - ./etc:/var/www/html/app/code/BitExpert/ForceCustomerLogin/etc:cached
      - ./Helper:/var/www/html/app/code/BitExpert/ForceCustomerLogin/Helper:cached
      - ./Model:/var/www/html/app/code/BitExpert/ForceCustomerLogin/Model:cached
      - ./Plugin:/var/www/html/app/code/BitExpert/ForceCustomerLogin/Plugin:cached
      - ./Repository:/var/www/html/app/code/BitExpert/ForceCustomerLogin/Repository:cached
      - ./Setup:/var/www/html/app/code/BitExpert/ForceCustomerLogin/Setup:cached
      - ./Ui:/var/www/html/app/code/BitExpert/ForceCustomerLogin/Ui:cached
      - ./Validator:/var/www/html/app/code/BitExpert/ForceCustomerLogin/Validator:cached
      - ./view:/var/www/html/app/code/BitExpert/ForceCustomerLogin/view:cached
      - ./registration.php:/var/www/html/app/code/BitExpert/ForceCustomerLogin/registration.php
      - ./var:/var/www/html/var
    ports:
      - 8000:80
    networks: &appnetworks
      - www
    environment:
      - APP_MAGE_MODE=developer

  phpfpm:
    image: mageinferno/magento2-php:7.0-fpm-1
    links:
      - db
    volumes: *appvolumes
    networks: *appnetworks
    environment:
      - PHP_MEMORY_LIMIT=4096M
      - APP_MAGE_MODE=developer

  db:
    image: percona:5.7
    volumes:
      - .docker/db:/var/lib/mysql:cached
    ports:
      - 8001:3306
    networks: *appnetworks
    env_file: env/mysql.env

  setup:
    image: mageinferno/magento2-php:7.0-fpm-1
    command: /usr/local/bin/mage-setup
    links:
      - db
    volumes: *appvolumes
    networks: *appnetworks
    env_file: env/setup.env

volumes:
  dbdata:
  appdata:

networks:
  www:
